CREATE SEQUENCE band_seq;

CREATE TABLE BAND (
ID int Primary Key,
NAME VarChar2(20) not null UNIQUE,
DATE_OF_FOUNDATION Date not null);

CREATE OR REPLACE TRIGGER band_trigger
BEFORE INSERT ON BAND FOR EACH ROW
BEGIN
:NEW.ID := band_seq.NEXTVAL;
END;