INSERT INTO BAND(NAME,DATE_OF_FOUNDATION) values('RedHotChilliPeppers',TO_DATE('01-08-1983'));
INSERT INTO BAND(NAME,DATE_OF_FOUNDATION) values('MUSE',TO_DATE('01-02-1994'));
INSERT INTO BAND(NAME,DATE_OF_FOUNDATION) values('IN FLAMES',TO_DATE('03-03-1990'));